## 1. range()函数

range()函数在python3的内置函数，是一个迭代器，类型变成了'range'，这是为了节省内存

In [2]:
print(type(range(0, 10)))

<class 'range'>


如果需要range的数据，可以利用list()，也可以利用np.array()

In [3]:
import numpy as np
print(list(range(0, 10)))
print(np.array(range(0, 10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


但是要注意，range()的步长只能是整数，否则会报错

In [4]:
range(8, 10, 0.1)

TypeError: 'float' object cannot be interpreted as an integer

## 2. np的arange()、linespace()、logspace()函数 

numpy的这三个函数是可以生成float数据的步长的，获得的结果类型是一个array

In [5]:
import numpy as np
print(np.arange(0, 1, 0.1))
print(type(np.arange(0, 1, 0.1)))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
<class 'numpy.ndarray'>


In [6]:
print(np.linspace(1, 10, 10))
print(type(np.linspace(1, 10, 10)))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [8]:
print(np.logspace(1, 10, 5))
print(type(np.logspace(1, 10, 5)))

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]
<class 'numpy.ndarray'>


他们也可以出现在循环中

In [11]:
a = [np.round(s**2, 2) for s in np.arange(8, 10, 0.1)]
print(a)

[64.0, 65.61, 67.24, 68.89, 70.56, 72.25, 73.96, 75.69, 77.44, 79.21, 81.0, 82.81, 84.64, 86.49, 88.36, 90.25, 92.16, 94.09, 96.04, 98.01]
