### （1）svd分解
任意一个矩阵A($ T \times n $)，可以进行如下分解：$ A = U \Sigma V^T $，其中U、$\Sigma$、V的维度为($ T \times T $)、($ T \times n $)、($ n \times n $)。

In [11]:
# 任意一个矩阵的奇异值分解的结果
import numpy as np
import numpy.linalg as la

A = np.array([[1, 2, 3, 4], [9, 8, 17, 6], [4, 7, 11, 8], [10, 4, 14, 2], [4, 7, 11, 15], [2, 8, 10, 5]])
U1, sigma1, VT1 = la.svd(A)  # svd分解
V1 = VT1.T

# 将分解得到的sigma1扩展为变成一个4X6和6X4的矩阵
sigma2 = np.zeros(6)
sigma2[:4] = sigma1
sigma2 = np.diag(sigma2)[:, 0:4]  # 把sigma1变成一个6X4的矩阵sigma2
sigma3 = np.zeros(6)
sigma3[:4] = 1/sigma1
sigma3 = np.diag(sigma3)[0:4, :]  # 把sigma1变成一个6X4的矩阵sigma3，奇异值为sigma2的倒数

print('例子矩阵A(6X4：假设T=6，n=4)：')
print(A)
print(f'A的秩：{la.matrix_rank(A)}')
print('矩阵A的分解结果：')
print('U1：')
print(U1)
print('sigma：')
print(sigma2)
print('V1：')
print(V1)

例子矩阵A(6X4：假设T=6，n=4)：
[[ 1  2  3  4]
 [ 9  8 17  6]
 [ 4  7 11  8]
 [10  4 14  2]
 [ 4  7 11 15]
 [ 2  8 10  5]]
A的秩：3
矩阵A的分解结果：
U1：
[[-0.12998873 -0.1787086  -0.08821125  0.96510126 -0.09518398  0.05389349]
 [-0.54818536  0.33166279  0.07101321  0.07868776  0.7208328  -0.2421942 ]
 [-0.40243945 -0.17245628  0.17107431 -0.07699982 -0.48218955 -0.73525449]
 [-0.41583446  0.62023011 -0.37310509 -0.03739684 -0.45972989  0.30073046]
 [-0.47992124 -0.66018    -0.4413247  -0.23268615  0.09967015  0.2738494 ]
 [-0.3426303  -0.08831099  0.7898953  -0.03028944 -0.13246739  0.48208505]]
sigma：
[[3.89264214e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.14961355e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.75106135e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 3.41030867e-15]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]]
V1：
[[-3.45182129e-01  4.78542

### （2）对分解结果的理解
（2.1）V的列向量$[v_1,...,v_k]$是矩阵$ A^T A $的特征向量（n维），U的列向量$[u_1,...,u_k]$是矩阵$ A A^T $的特征向量（T维），其中k=rank(A)；<br/>
（2.2）V和U的分解结果是($ n \times n $)和($ T \times T $)，多出来的列是什么呢？<br/>
python的SVD的规范结果：<br/>
列向量$[v_{k+1},...,v_n]$是$ A^T A \vec x = \vec 0 $的解空间的基，或称$ A^T A $的零空间的基；<br/>
列向量$[u_{k+1},...,u_T]$是$ A A^T \vec x = \vec 0 $的解空间的基，或称$ A A^T $的零空间的基；<br/>
实际上，还可以：<br/>
随意取值。python的规范结果，只是为了能够让U和V成为一个标准的正交矩阵。

In [16]:
ATA = np.dot(A.T, A)
AAT = np.dot(A, A.T)

# 理解U和V是特征向量矩阵
### V
##### ATA的svd分解结果
V2, S_ATA, VT2 = la.svd(ATA)
##### 利用UT*R = Sigma*VT倒算的结果
V3 = np.dot(np.dot(sigma3, U1.T), A).T
##### 最后(n-k)(4-3=1)列填写任意值
V4 = V1.copy()
V4[:, 3] = np.array([1, 2, 3, 7])

a1 = np.dot(ATA, V1)
a2 = np.dot(ATA, V2)
a3 = np.dot(ATA, V3)
a4 = np.dot(ATA, V4)

print('对ATA进行svd分解，得到的特征矩阵V2：')
print(V2)
print('利用公式倒算的特征矩阵V3：')
print(V3)
print('非特征向量列给予任意值的V4：')
print(V4)
print('ATA与V1的点乘：')
print(a1)
print('ATA与V2的点乘：')
print(a2)
print('ATA与V3的点乘：')
print(a3)
print('ATA与V4的点乘：')
print(a4)

### 利用U1\Vn对数据复原
A1 = np.dot(np.dot(U1, sigma2), V1.T)
A3 = np.dot(np.dot(U1, sigma2), V3.T)
A4 = np.dot(np.dot(U1, sigma2), V4.T)
print('利用V1复原的结果')
print(A1)
print('利用V3复原的结果')
print(A3)
print('利用V4复原的结果')
print(A4)

对ATA进行svd分解，得到的特征矩阵V2：
[[-3.45182129e-01  4.78542598e-01  5.64369512e-01 -5.77350269e-01]
 [-3.91157598e-01 -1.52932813e-01 -7.00195655e-01 -5.77350269e-01]
 [-7.36339727e-01  3.25609785e-01 -1.35826142e-01  5.77350269e-01]
 [-4.30869861e-01 -8.00991139e-01  4.15649321e-01 -5.61096011e-16]]
利用公式倒算的特征矩阵V3：
[[-0.34518213  0.4785426  -0.56436951 -0.8125    ]
 [-0.3911576  -0.15293281  0.70019565  0.7265625 ]
 [-0.73633973  0.32560978  0.13582614 -0.1875    ]
 [-0.43086986 -0.80099114 -0.41564932  1.171875  ]]
非特征向量列给予任意值的V4：
[[-0.34518213  0.4785426  -0.56436951  1.        ]
 [-0.3911576  -0.15293281  0.70019565  2.        ]
 [-0.73633973  0.32560978  0.13582614  3.        ]
 [-0.43086986 -0.80099114 -0.41564932  7.        ]]
ATA与V1的点乘：
[[-5.23042842e+02  6.32447311e+01 -1.27392782e+01 -2.84217094e-14]
 [-5.92707921e+02 -2.02117736e+01  1.58052252e+01 -2.84217094e-14]
 [-1.11575076e+03  4.30329575e+01  3.06594700e+00 -5.68434189e-14]
 [-6.52882574e+02 -1.05859895e+02 -9.38227918e+00 -2.84

In [18]:
### U
##### AAT的svd分解结果
U2, S_AAT, UT2 = la.svd(AAT)
##### 利用R*V = U*Sigma倒算的结果
U3 = np.dot(np.dot(A, VT1.T), sigma3)
##### 最后(T-k)(6-3=3)列填写任意值
U4 = U1.copy()
U4[:, 3:] = np.arange(18).reshape(6, 3)

a1 = np.dot(AAT, U1)
a2 = np.dot(AAT, U2)
a3 = np.dot(AAT, U3)
a4 = np.dot(AAT, U4)

print('对AAT进行svd分解，得到的特征矩阵U2：')
print(U2)
print('利用公式倒算的特征矩阵U3：')
print(U3)
print('非特征向量列给予任意值的U4：')
print(U4)
print('AAT与U1的点乘：')
print(a1)
print('AAT与U2的点乘：')
print(a2)
print('AAT与U3的点乘：')
print(a3)
print('AAT与U4的点乘：')
print(a4)

### 利用Un\V1对数据复原
A1 = np.dot(np.dot(U1, sigma2), V3.T)
A3 = np.dot(np.dot(U3, sigma2), V3.T)
A4 = np.dot(np.dot(U4, sigma2), V3.T)
print('利用U1复原的结果')
print(A1)
print('利用U3复原的结果')
print(A3)
print('利用U4复原的结果')
print(A4)

对AAT进行svd分解，得到的特征矩阵U2：
[[-0.12998873  0.1787086   0.08821125  0.96986879 -0.04231856  0.03079943]
 [-0.54818536 -0.33166279 -0.07101321 -0.02028223 -0.63694976 -0.42229535]
 [-0.40243945  0.17245628 -0.17107431 -0.02274083  0.66262739 -0.58261711]
 [-0.41583446 -0.62023011  0.37310509  0.02759338  0.36657975  0.4099351 ]
 [-0.47992124  0.66018     0.4413247  -0.2400588  -0.13792081  0.24984014]
 [-0.3426303   0.08831099 -0.7898953  -0.00603198  0.00512126  0.50080779]]
利用公式倒算的特征矩阵U3：
[[-0.12998873 -0.1787086  -0.08821125 -0.13021965  0.          0.        ]
 [-0.54818536  0.33166279  0.07101321 -0.2604393   0.          0.        ]
 [-0.40243945 -0.17245628  0.17107431 -0.2604393   0.          0.        ]
 [-0.41583446  0.62023011 -0.37310509 -0.39065896  0.          0.        ]
 [-0.47992124 -0.66018    -0.4413247  -0.52087861  0.          0.        ]
 [-0.3426303  -0.08831099  0.7898953   0.          0.          0.        ]]
非特征向量列给予任意值的U4：
[[-0.12998873 -0.1787086  -0.08821125  0.   

In [10]:
# 综合一下U和V，取它们的前k列
U5 = U1.copy()
U5 = U1[:, 0:3]
V5 = V1.copy()
V5 = V1[:, 0:3]
sigma5 = np.diag(sigma1[0:3])
A5 = np.dot(np.dot(U5, sigma5), V5.T)

print('U5：')
print(U5)
print('sigma5：')
print(sigma5)
print('V5：')
print(V5)
print('用它们还原得到的A5：')
print(A5)

U5：
[[-0.12998873 -0.1787086  -0.08821125]
 [-0.54818536  0.33166279  0.07101321]
 [-0.40243945 -0.17245628  0.17107431]
 [-0.41583446  0.62023011 -0.37310509]
 [-0.47992124 -0.66018    -0.4413247 ]
 [-0.3426303  -0.08831099  0.7898953 ]]
sigma5：
[[38.92642142  0.          0.        ]
 [ 0.         11.49613549  0.        ]
 [ 0.          0.          4.75106135]]
V5：
[[-0.34518213  0.4785426  -0.56436951]
 [-0.3911576  -0.15293281  0.70019565]
 [-0.73633973  0.32560978  0.13582614]
 [-0.43086986 -0.80099114 -0.41564932]]
用它们还原得到的A5：
[[ 1.  2.  3.  4.]
 [ 9.  8. 17.  6.]
 [ 4.  7. 11.  8.]
 [10.  4. 14.  2.]
 [ 4.  7. 11. 15.]
 [ 2.  8. 10.  5.]]
